apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki-ingestorx
    access: proxy
    url: http://loki:3100
    isDefault: true
    version: 1
    editable: false
  - name: Prometheus
    type: prometheus
    uid: prometheus-ingestorx
    access: proxy
    url: http://host.docker.internal:19090
    isDefault: false
    version: 1
    editable: false
